[package]
name = "odj-cbor"
version = "0.1.0"
authors = ["megam"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half = "1.3.0"